#!/bin/sh -e

# All available environment variables: https://gitlab.com/craftyguy/networkd-dispatcher

# exit on ifname not start with 'ppp'
# comment out fllow line if not needed.
case $IFACE in ppp*) ;; *) exit 0 ;; esac

export ACCESS_KEY_ID="<access key id>"
export ACCESS_KEY_SECRET="<access key secret>"

DOMAIN=router.example.com

alidnsctl set ${DOMAIN} ${ADDR}
alidnsctl set --type AAAA ${DOMAIN} ${IP6_ADDRS}
